import 'server-only'

import { consoleObjectStore } from '@/lib/console/images'
import { isProtectedKey } from '@/lib/retention/protected-keys'
import { supabaseServer } from '@/lib/supabase/server'

/**
 * Discard a held photograph for good.
 *
 * The ORDER is the whole design:
 *
 *   1. delete its generated R2 objects
 *   2. delete the database row
 *
 * Deleting R2 before the claim would leave a queue row pointing at images that
 * no longer load. Every step before the last is idempotent, so a failure
 * part-way leaves the row intact and the operator simply presses Discard again.
 * (D144: the Drive move that used to come first is gone with the Drive inbox.)
 */
export async function discardHeldIntake(
  intakeFileId: string,
  actor: string,
): Promise<{ objectsDeleted: number }> {
  const db = supabaseServer()

  const { data: file, error: fileError } = await db
    .from('intake_files')
    .select('id, status, filename, product_draft_id')
    .eq('id', intakeFileId)
    .maybeSingle<{ id: string; status: string; filename: string; product_draft_id: string | null }>()
  if (fileError) throw new Error(`intake_files: ${fileError.message}`)
  if (!file) throw new Error('That photograph no longer exists.')

  // Checked here for a readable message, and again inside discard_intake_file()
  // so nothing reaching the database another way can route around it (D18).
  if (file.status !== 'skipped') {
    throw new Error('Only a photograph that is on hold can be discarded.')
  }

  const { data: versions, error: versionError } = await db
    .from('image_versions')
    .select('storage_key, thumb_key, purged_at')
    .eq('intake_file_id', intakeFileId)
  if (versionError) throw new Error(`image_versions: ${versionError.message}`)

  // 1. The generated bytes. Already-purged rows have nothing left to delete.
  // The ORIGINAL is kept: it is the only real photograph of the piece and the
  // SKU matcher's reference (D109). Its key stays recoverable from the
  // `intake.discarded` event, whose entity_id is the intake id the key is
  // named after.
  const store = consoleObjectStore()
  let objectsDeleted = 0
  for (const version of (versions ?? []) as {
    storage_key: string | null
    thumb_key: string | null
    purged_at: string | null
  }[]) {
    if (version.purged_at) continue
    for (const key of [version.storage_key, version.thumb_key]) {
      if (!key || isProtectedKey(key)) continue
      await store.delete(key)
      objectsDeleted += 1
    }
  }

  // 2. Finally the row. This audits before deleting.
  const { error: discardError } = await db.rpc('discard_intake_file', {
    p_intake_file_id: intakeFileId,
    p_actor: actor,
  })
  if (discardError) {
    throw new Error(
      `${file.filename}'s generated images were deleted, but the record could not be ` +
        `removed: ${discardError.hint || discardError.message}. Press Discard again.`,
    )
  }

  return { objectsDeleted }
}
